const actions = {
  CREATE_TASK: "CREATE_TASK_SUCCESS",
  READ_TASKS: "READ_TASKS_SUCCESS",
  UPDATE_TASK: "UPDATE_TASK_SUCCESS",
  DELETE_TASK: "DELETE_TASK",
  GET_TASK_BY_ID: "GET_TASK_BY_ID_SUCCESS",
  GET_TASK_STATUS_OPTIONS_SUCCESS: "GET_TASK_STATUS_OPTIONS_SUCCESS",
  GET_TASK_INTERFACE_SUCCESS: "GET_TASK_INTERFACE_SUCCESS",
  SET_TASK_COUNT: "SET_TASK_COUNT"
}

export default actions
